server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_USERNAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  web:
    resources:
      static-locations: classpath:/productimgs/
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database: oracle
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${{ secrets.JWT_SECRET }}


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: secretjuju.gaemihouse
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

