name: Java CI with Maven And Build And Push Docker Image

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Set application.yml from Secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }} 
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }} 
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }} 
        jwt.secret: ${{ secrets.JWT_SECRET }}    
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME_CDH }} -p ${{ secrets.DOCKER_PASSWORD_CDH }}
      
    - name: Build DockerImage
      run: docker build -t ${{ secrets.DOCKER_HUB_NAME_CDH }}/backend:latest ./
        
    - name: Push DockerImage
      run: docker push ${{ secrets.DOCKER_HUB_NAME_CDH }}/backend:latest

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
